version: "3.9"

services:
  parallel-bot:
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: python main.py --log-level=debug parallel-trader --exchange-name=binance --trading-strategies=period-max

  serial-bot:
    build: .
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: python3 main.py --log-level=info serial-trader --exchange-name=binance --trading-strategies=bollinger

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
