version: "3.9"
services:
  tradding-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
        - ./.env
    volumes:
        - .:/worker
    command: python main.py parallel-trader
