# Bots

serialTrader:
  cycleTime: 15
  assetToTrade: ADA
  baseAsset: USDT
  baseAssetUsagePercentage: 100
  stopLossPercentage: 2
  stopGainPercentage: 2
  plotResults: false

# Trading Strategies

bollinger:
  minRelativeBandsDelta: 0.04

# Exchanges

binance:
  intervalInMinutes: 1
  taxPerTransaction: 0.075
  api:
    key: "sample-api-key"
    secret: "sample-api-secret"

binanceSimulator:
  intervalInMinutes: 3
  numberOfIntervals: 20000
