# Bots

serialTrader:
  cycleTimeInSeconds: 15
  candleSizeInMinutes: 1
  candlesToRetrievePerCycle: 200
  assetToTrade: ADA
  baseAsset: USDT
  baseAssetUsagePercentage: 100
  stopLossPercentage: 2
  stopGainPercentage: 2
  plotResults: false

parallelTrader:
  cycleTimeInSeconds: 15
  candleSizeInMinutes: 1
  baseAsset: USDT
  baseAssetAmountPerTrade: 15
  stopLossPercentage: 10
  stopGainPercentage: 10

# Trading Strategies

bollinger:
  minRelativeBandsDelta: 0.04

periodMax:
  # NOTE: candle (aka interval) size is defined by bots.
  # NOTE: this value will be converted to days and rounded up.
  numIntervals: 28800
  secondsToUpdateCache: 600
  cacheUpdater:
    enabled: true

# Exchanges

binance:
  taxPerTransaction: 0.075
  api:
    key: "sample-api-key"
    secret: "sample-api-secret"

backtest:
  taxPerTransaction: 0.075
  totalNumberOfIntervals: 10000
  startIntervalIndex: 200

# Other dependencies

redis:
  host: localhost
  port: 6379
