# Bots

serialTrader:
  cycleTimeInSeconds: 15
  assetToTrade: ADA
  baseAsset: USDT
  baseAssetUsagePercentage: 100
  stopLossPercentage: 2
  stopGainPercentage: 2
  plotResults: false

parallelTrader:
  cycleTimeInSeconds: 15
  baseAsset: USDT
  baseAssetAmountPerTrade: 12
  stopLossPercentage: 10
  stopGainPercentage: 10

# Trading Strategies

bollinger:
  minRelativeBandsDelta: 0.04

periodMax:
  periodUsedInDays: 20
  secondsToUpdateCache: 600
  cacheUpdater:
    enabled: true

# Exchanges

binance:
  intervalInMinutes: 1
  taxPerTransaction: 0.075
  api:
    key: "sample-api-key"
    secret: "sample-api-secret"

binanceSimulator:
  intervalInMinutes: 3
  numberOfIntervals: 20000

# Other dependencies

redis:
  host: localhost
  port: 6379
